# the version of docker compose parser 
version: "3.9"

services:
  # service name
  ollama-langchain:
    # image name
    image: fc-langchain-rag:v0.1.6
    container_name: fc-rag-stg
    build:
      context: .
      dockerfile: Dockerfile.stg
    ports:
      - "11450:11434"
      - "8000:8000"
    volumes:
      - ../../workspace:/workspace
      - ollama:/root/.ollama
    logging:
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log" # sent Log to localhost's Syslog Socket
        tag: "{{.Name}}"  # identify container with tag {{.Name}} for container's name
        syslog-format: "rfc3164" # (Opt.) set Log format
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all          # specify counts(ex. 1)
              capabilities: [gpu]
              
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_HOST=0.0.0.0
      - PYTHONUNBUFFERED=1
    #tty: true
    #stdin_open: true

volumes:
  ollama:               # the name of volume